---
- name: Install python3, docker, docker-compose
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars:
        ansible_python_interpreter: /usr/bin/python
      ansible.builtin.yum:
        name:
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}} ## pipe is ansible lookup plugin
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose

- name: Add {{ linux_name }} to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add {{ linux_name }} to docker group
      ansible.builtin.user:
        name: {{ linux_name }}
        groups: docker
        append: yes
    - name: Reconnect to server session
      ansible.builtin.meta: reset_connection


- name: Start docker containers
  hosts: docker_server
  vars_files:
    - nodejs-vars
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: /Users/{{ linux_name }}docker-compose.yaml
        dest: /home/{{ linux_name }}/docker-compose.yaml
    - name: Docker login
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: {{ linux_name }}
        password: "{{ docker_password }}"
    - name: Start container from compose
      community.docker.docker_compose:
        project_src: /home/{{ linux_name }}

