- name: configure webservice and databses servers
- hosts: webservers
  remote_user: root
  vars:
    servername: nginx

  tasks:
    - name: create directory for {{ servername }}
      file:
        path: /data/ngixn/dir
        state: directory

    - name: install {{ servername }} latest version
      apt:
        name: {{ servername }}
        state: latest

    - name: start {{ servername }}
      service:
        name: {{ servername }}
        state: started

    - name: stop {{ servername }}
      service:
        name: {{ servername }}
        state: stop

    - name: uninstall {{ servername }} latest version
      apt:
        name: {{ servername }}
        state: stoped

- hosts: databases
  remote_user: root

  tasks:
    - name: rename table
      postgresql_table:
        table: clients
        rename: customers

    - name: set Owner to someuser
      postgresql_table:
        name: clients
        owner: Amir

    - name: truncate table customers
      postgresql_table:
        name: clients
        truncate: yes


#ansible-playbook -i hosts syntax.yaml